# Site settings
title: Jekyll Doc Theme
email: your-email@domain.com
description: >
  Testing the Jekyll Doc Theme.
lang: en-GB

baseurl: "/" # the subpath of your site, e.g. /blog/
url: https://chlorenz.github.io # the base hostname & protocol for your site
git_address: https://github.com/chlorenz/chlorenz.github.io.git
git_edit_address: https://github.com/chlorenz/chlorenz.github.io.git/blob/master

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: yeti # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

whitelist:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md

timezone: Europe/Berlin

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

# Google Analytics
#google_analytics: XX-XXX-X