destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/docs-pdf"
port: 4010
output: pdf
product: docs
print_title: The best test project — pdf test
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: docs_sidebar
